### ISSUE TITLE
Error in curl_fetch_memory(url, handle = h) : Login denied

### ISSUE THREAD

**Issue by GabriellaSpence** [datawookie/emayili#48]
Hi Andrew, 

I saw #45 and logged in successfully by manually typing in info. Does this package work for Office 365 Business? 

smtp <- server(host = "smtp.office365.com",
               port = 587,
               username = "",
               password = "")

Thanks, 
Gabriella

**Comment by datawookie** [comment]
Hi @GabriellaSpence,

> Does this package work for Office 365 Business?

I'm really not sure because I don't have access to a Office 365 Business account. But I'd be very happy to work with you to iron out any issues. I see no reason why it shouldn't!

Please let me know what you have tried and what issues you have experienced.

Best regards,
Andrew.

**Comment by GabriellaSpence** [comment]
Hi Andrew, 

I don't know really know anything about SMTPs, so I most likely won't be much help here. I only tried just the basic test email (replacing emails and username/pass). 

```
library(emayili)
library(dplyr)

email <- envelope() %>%
  from("my email") %>%
  to("another email") %>%
  subject("Test email subject") %>%
  text("Hello! Testing sending email from R script.")

smtp <- server(host = "smtp.office365.com",
               port = 587,
               username = "",
               password = "")

smtp(email, verbose = TRUE)
```

Which prints out this in the console:

```
Sending email to  smtp://smtp.office365.com:587/ .
  Trying 52.96.90.50...
TCP_NODELAY set
Connected to smtp.office365.com (52.96.90.50) port 587 (#0)
220 BL1PR13CA0060.outlook.office365.com Microsoft ESMTP MAIL Service ready at Mon, 20 Jul 2020 16:24:52 +0000
EHLO 5CD8150Y3P
250-BL1PR13CA0060.outlook.office365.com Hello [67.102.243.138]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
STARTTLS
220 2.0.0 SMTP server ready
EHLO 5CD8150Y3P
250-BL1PR13CA0060.outlook.office365.com Hello [67.102.243.138]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
AUTH LOGIN
334 VXNlcm5hbWU6
Z3NwZW5jZUBldm9sZW50aGVhbHRoLmNvbQ==
334 UGFzc3dvcmQ6
MzJueENpbzA4
535 5.7.3 Authentication unsuccessful [BL1PR13CA0060.namprd13.prod.outlook.com]
Closing connection 0
schannel: shutting down SSL/TLS connection with smtp.office365.com port 587
Error in curl_fetch_memory(smtp_server, handle = h) : Login denied
```

Best, 
Gabriella

**Comment by datawookie** [comment]
Hi Gabriella,

Okay, well it looks like `{emayili}` is able to communicate with your SMTP server fine.

However, you're not able to send email because you're not authenticating properly (hence the "Login denied" message). I really don't know much about Office365, but generally the problem in this situation is either:

(1) the credentials that you're using are not correct or
(2) there's some weird configuration somewhere.

I'm guessing that it's (1).

Can you please check that the username and password that you're supplying to `server()` are correct?

- Sometimes the username is not what you expect. For example, it might be "gabriella" or it might be "gabriella@example.com" (obviously with the correct domain). Please try a few options. What username do you use if you connect to webmail?
- Please check that the password is correct.

Thanks, Andrew.

**Comment by GabriellaSpence** [comment]
Hi Andrew, 

Yes, it works, but now actually thinking about it, two-factor authentication is turned on because I always get prompted on my phone to enter a password when logging on to a new browser (when signing in with incognito mode). I don't remember setting this up so it must have been set up by default with my organization. Do you think this could be the issue and assuming I can't turn this off, is there a way to work around two-factor authentication?

Best, 
Gabriella

**Comment by datawookie** [comment]
Hi Gabriella,

Hmmm. I'm afraid I just have no idea how one could get around two-factor authentication with `{emayili}`. The nature of 2FA is that it requires you to independently verify yourself on another device/medium, so I can't immediately think of a way that we could handle that from within the package. Sorry!

> Yes, it works.

I'm going to close this issue, but very happy to continue the discussion here if it would be helpful.

Best regards, Andrew.
