### ISSUE TITLE
From field can be anything, is that normal?

### ISSUE THREAD

**Issue by aavanesy** [datawookie/emayili#64]
Hi,
I am using actively the package for a couple of months.
Today was changing some code by accident typed my personal email in `from` instead of the email in `stmp`.
My biggest suprise was that the email was sent through and I received an email to my inbox.

Next I tried typing some random emails, and it worked again. Finally I typed this

    email <- email %>%
      from("helloworld") %>%
      to(mymail)

And this is what I have in my inbox

![image](https://user-images.githubusercontent.com/48486871/111062097-47e96f00-84c0-11eb-8a7c-69b408d3c629.png)

So sender is basically `helloworld`, not a real email, doesn't say it was forwarded from the server or anything.

Is this something to do with the package? Should I correct the settings?

**Comment by datawookie** [comment]
Hi Arkadi,

Thanks for raising this.

According to [RFC 2822](https://tools.ietf.org/html/rfc2822):

> In all cases, the "From:" field SHOULD NOT contain any mailbox that does not belong to the author(s) of the message.

So, indeed, the `From:` field _should not_ be set to an invalid address.

However, it's important to allow the possibility of the `From:` field differing from the email address being used to send the email.

The `Sender:` field caters for the possibility of somebody sending an email _on behalf of_ somebody else. For example, `bob@gmail.com` sends a message on behalf of `carol@gmail.com`, in which case one would have:

```
Sender: bob@gmail.com
From: carol@gmail.com
```

And in this case the actual email would originate from Bob's email account.

I stand to be corrected on this, but my feeling is that rules relating to email header fields should be enforced by the server rather than the client (where the client in this case is `{emayili}`).

Best regards, Andrew.

**Comment by aavanesy** [comment]
Hi Andrew,

Thank you for the answer.

I suppose the email does create some sort of digital signature specifying who was the real sender?

**Comment by datawookie** [comment]
Well, kind of.

Here's an example of an email which I sent via Gmail where I specified `carol@gmail.com` (not my email address) as the `From:` field. I've obfuscated the places where my actual email appears. Gmail gives `carol@gmail.com` in the `X-Google-Original-From:` field but uses my actual email address elsewhere.

So I guess that the behaviour depends on the SMTP server.

![image](https://user-images.githubusercontent.com/6134409/111111249-aff29080-8566-11eb-9253-8ed0024f73cd.png)
