### ISSUE TITLE
The recipient address is not a valid RFC-5321 address

### ISSUE THREAD

**Issue by ceciliacronemberger** [datawookie/emayili#72]
Hi. I´m using Emayili to send a large number of emails retrieving information from a very large spreadsheet. My code worked for the first 2 emails, but then I staretd getting this error:  

553 5.1.3 The recipient address is not a valid RFC-5321 address

Any thoughts? Thanks!

**Comment by datawookie** [comment]
Hi @ceciliacronemberger,

This sounds like you have some malformed email addresses in your data. Without more details, I can only guess at what the problem might be. Perhaps you can provide more context? Have you sent an email with debugging output enabled? Could you please provide that? You are welcome to obfuscate the email addresses (but please only change the email address and none of the surrounding syntax, which I think is going to be important for ironing out the problem here.

In the meantime though, I've made some updates on the development branch. Would you mind testing those out?

You can install using the following:

```r
remotes::install_github("datawookie/emayili", ref = "5dad4c695414b17a2c43bed329a16d45fc375495")
```

Thanks, Andrew.

**Comment by datawookie** [comment]
Any feedback on this, @ceciliacronemberger?
